# -*- coding: utf-8 -*-
"""Lab6 Пирсон.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ejmKIgD6OF2Yt4Se1UrVbCgUbz0--a7
"""

import random
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

m = 6 # для нормального
def calc(N,C,M):
  x = [0]*N
  z = [0]*N
  n = [0]*6
  zh = [0]*7 # границы частичных интервалов: числа Xmin, Xmin+h, ..., Xmax
  for i in range(int(N)):
    for j in range(12):
      x[i] =random.random() +x[i]
    x[i] = x[i] - 6
    z[i] = C*x[i] + M
    # print(f'{x[i]}\t {z[i]}')
  zmin, zmax = min(z), max(z)
  h = (zmax-zmin)/m
  print('zmin= ',zmin,'zmax= ',zmax, 'h= ', h, '\n')
  zh[0] = zmin
  for i in range(1, 6):
    zh[i] = zh[i-1] + h  
  zh[6] = zmax
  # p = [0, 0.0215, 0.3385, 0.6788, 1.0185, 1.1555, 1.177]
  z.sort()
  for i in range(N):
    for j in range(6):
      if zh[j] <= z[i] <= zh[j+1]: 
        n[j] = n[j] + 1
        # print(f'{i}:\t{zh[j]} < {z[i]} <= {zh[j+1]}\t n{j}={n[j]}')
        break
      # if z[i] == zmin: n[1] += 1
  return x, z, n, zh

# for N in [10, 100, 500, 1000]:
# N = int(input("Введите N: \n"))
# M = float(input("Введите M: \n"))
# D = float(input("Введите D: \n"))
# С = float(input("Введите c: \n"))
N=100
M=0
C=1
x, z, n, zh = calc(N, C, M)
p = [0.0215, 0.137, 0.34, 0.34, 0.137, 0.0215]
zmin, zmax = min(z), max(z)
h = (zmax-zmin)/6
c=0
for i in range(6):
  # print(f'{i}:\t {(n[i] - N*p[i])*(n[i] - N*p[i])}\t{N*p[i]}\t{(n[i] - N*p[i])*(n[i] - N*p[i]) / (N*p[i])}')
  print(f'{i}:\t {n[i]}\t{N*p[i]}')
  c = c + (n[i] - N*p[i])**2 / (N*p[i])

print(c)  
sns.histplot(z, bins=6, kde=True);

print(*n, sep='\t')
print(*p, sep='\t')
print(*z)
print(*zh)
